config/routes.rb
Rails.application.routes.draw do
  root to: 'clones#index'
  resources :clones do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clone.rb
class Clone < ApplicationRecord
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clones_controller.rb
class ClonesController < ApplicationController
  before_action :set_clone, only: %i[show edit update destroy]

  # GET /clones
  # GET /clones.json
  def index
    @clones = Clone.all
  end

  # GET /clones/1
  # GET /clones/1.json
  def show; end

  # GET /clones/new
  def new
    @clone = if params[:back]
               Clone.new(clone_params)
             else
               Clone.new
             end
  end

  # GET /clones/1/edit
  def edit; end

  # POST /clones
  # POST /clones.json
  def create
    @clone = Clone.new(clone_params)

    respond_to do |format|
      if @clone.save
        format.html { redirect_to @clone, notice: 'Clone was successfully created.' }
        format.json { render :show, status: :created, location: @clone }
      else
        format.html { render :new }
        format.json { render json: @clone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clones/1
  # PATCH/PUT /clones/1.json
  def update
    respond_to do |format|
      if @clone.update(clone_params)
        format.html { redirect_to @clone, notice: 'Clone was successfully updated.' }
        format.json { render :show, status: :ok, location: @clone }
      else
        format.html { render :edit }
        format.json { render json: @clone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clones/1
  # DELETE /clones/1.json
  def destroy
    @clone.destroy
    respond_to do |format|
      format.html { redirect_to clones_url, notice: 'Clone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @clone = Clone.new(clone_params)
    render :new if @clone.invalid?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_clone
    @clone = Clone.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def clone_params
    params.require(:clone).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clones_helper.rb
module ClonesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_clones_path
    elsif action_name == "edit"
      clone_path
    end
  end
end

app/views/clones/_form.html.erb
<%= form_with(model: clone, local: true, url: choose_new_or_edit ) do |form| %>
  <% if clone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clone.errors.count, "error") %> prohibited this clone from being saved:</h2>

      <ul>
      <% clone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clones/confirm.html.erb
<h3>以下の内容で、投稿しますか？</h3>

<%= form_with(model: @clone, url: clones_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>つぶやき:<%= @clone.content %></p>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @clone, url: new_clone_path , local: true , method:"get")do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "戻る"  , name:"back"%>
  <% end %>

app/views/clones/edit.html.erb
<h1>編集画面 Clone</h1>

<%= render 'form', clone: @clone %>


<%= link_to '一覧画面へ戻る', clones_path %>

app/views/clones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clones</h1>

<table>
  <thead>
    <tr>
      <th>つぶやき</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clones.each do |clone| %>
      <tr>
        <td><%= clone.content %></td>
        <td><%= link_to '詳細', clone , class: "btn btn-default" %></td>
        <td><%= link_to '編集', edit_clone_path(clone), class: "btn btn-info" %></td>
        <td><%= link_to '削除', clone, method: :delete, data: { confirm: '本当に消しちゃう?' }, class: "btn btn-warning"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規投稿', new_clone_path %>

app/views/clones/new.html.erb
<h1>新規投稿 Clone</h1>

<%= render 'form', clone: @clone %>

<%= link_to '一覧画面へ戻る', clones_path %>

app/views/clones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @clone.content %>
</p>

<%= link_to '編集', edit_clone_path(@clone) %> |
<%= link_to '一覧へ戻る', clones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Bootstrap</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">clone1</a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to clones_path do %>
                <p>一覧</p>
                <%= mi.view_module %>
              <% end %>
            </li>
            <li><%= link_to new_clone_path do %>
              <p>新規投稿</p>
              <%= mi.comment %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>


</header>
<section class="main-header">
    <%= image_tag("achieve.png", :alt => 'achieve imag') %>
</section>
<section class="about">
  <h1>About clone</h1>
  <p>
    思うがままに呟いて、後で見返してみるかもしれません
  </p>
</section>

<%= yield %>
<footer class="container-fluid navbar navbar-default">
  <p>運営会社 kobayashi株式会社</p>
  <p>© 2017-2018 Copyright kohei kobayashi</p>
</footer>
</body>
</html>